site_name: CertiK Foundation Hub
site_description: Essential source for CertiK Chain information.
theme:
  name: "material"
  language: "en"
  palette:
    primary: "amber"
    accent: "amber"
  logo: "img/favicon.ico"
  favicon: "img/favicon.ico"
extra:
  social:
    - type: "github"
      link: "https://github.com/certikfoundation/chain"
copyright: "Copyright &copy; 2019-2020 CertiK Foundation"
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
nav:
  - What is CertiK Chain: index.md
  - Installation: installation.md
  - Join the Testnet: participate.md
  - Command-Line Interface: cli.md
